### ISSUE TITLE
Support for OCI charts.

### ISSUE THREAD

**Issue by marcusramberg** [nix-community/nixhelm#1]
the `helmupdater` script assumes the repo URL is http based, so it gets very unhappy if you try to provide a OCI url like  `oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller`

```
Traceback (most recent call last):

  File "/nix/store/v77qq44nrsvmxm1vpn2x627ds232fbf9-python3.10-helmupdater-0.1.0/bin/.helmupdater-wrapped", line 9, in <module>
    sys.exit(app())

  File "/nix/store/v77qq44nrsvmxm1vpn2x627ds232fbf9-python3.10-helmupdater-0.1.0/lib/python3.10/site-packages/helmupdater/__init__.py", line 177, in init
    update_one_chart(repo_name, chart_name, local_chart, commit=False)

  File "/nix/store/v77qq44nrsvmxm1vpn2x627ds232fbf9-python3.10-helmupdater-0.1.0/lib/python3.10/site-packages/helmupdater/__init__.py", line 58, in update_one_chart
    index_req = requests.get(f'{repo_url}index.yaml')

  File "/nix/store/5yalgwpfsg6rlfhwx78rdl03gg7pysyh-python3.10-requests-2.28.2/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)

  File "/nix/store/5yalgwpfsg6rlfhwx78rdl03gg7pysyh-python3.10-requests-2.28.2/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)

  File "/nix/store/5yalgwpfsg6rlfhwx78rdl03gg7pysyh-python3.10-requests-2.28.2/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)

  File "/nix/store/5yalgwpfsg6rlfhwx78rdl03gg7pysyh-python3.10-requests-2.28.2/lib/python3.10/site-packages/requests/sessions.py", line 695, in send
    adapter = self.get_adapter(url=request.url)

  File "/nix/store/5yalgwpfsg6rlfhwx78rdl03gg7pysyh-python3.10-requests-2.28.2/lib/python3.10/site-packages/requests/sessions.py", line 792, in get_adapter
    raise InvalidSchema(f"No connection adapters were found for {url!r}")

requests.exceptions.InvalidSchema: No connection adapters were found for 'oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller/index.yaml'
```

**Comment by farcaller** [comment]
status update: I'm working on this. The plan is to rewrite the updater in go and reuse the helm code to stop second-guessing.

**Comment by farcaller** [comment]
Ok, now it's _actually_ happening 😄 

I've rewritten [nixdockertag](https://github.com/farcaller/nixdockertag/commit/8eaf555dba96564cf8c6a24f4a362a8469a3afa8) in go now, and that's pretty much all the machinery required to support the OCI in here as well.

**Comment by kalbasit** [comment]
Is this issue still relevant? I know [downloadHelmChart](https://github.com/farcaller/nix-kube-generators/blob/810dcf792081790648ba9ae705b9a2286115ace8/lib/default.nix#L45) is working well.

**Comment by jkuball** [comment]
Yes, having this would be really great. Most Charts are still available via https, so that is not a big issue, but at least one chart that I know and use (the [grafana-operator](https://github.com/grafana/grafana-operator)) is only availabe via oci.

**Comment by e1senh0rn** [comment]
It is done! https://github.com/nix-community/nixhelm/pull/74 finally introduced the OCI support!
